# Generated by Django 3.2.9 on 2022-01-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='User name')),
                ('group', models.CharField(max_length=30, verbose_name='Group')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
