# Generated by Django 3.2.9 on 2022-01-24 20:27

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(username="User", group="One").save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_data),
    ]