version: '3'


services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start