# Generated by Django 3.2.9 on 2022-01-24 21:43

from django.db import migrations


def create_data(apps, schema_editor):
    Group_users = apps.get_model('groupusers', 'User')
    Group_users(name="Group user", description="One group").save()


class Migration(migrations.Migration):

    dependencies = [
        ('groupusers', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_data),
    ]